### PR TITLE
New version of use-query-params to pickup #244 in fixed serialize-query-params

### PR DESCRIPTION
**Pull request by jmcpeak**
New version of use-query-params 2.1.2 to pickup #244 in fixed serialize-query-params 2.0.2

### CODE REVIEW

**Comment by jonobral** [comment]
👍

**Comment by pbeshai** [comment]
Shouldn't this automatically work if you just reinstall the lib / clear it out from your package lock files?

**Comment by jmcpeak** [comment]
> Shouldn't this automatically work if you just reinstall the lib / clear it out from your package lock files?

I would have thought so as well, but our Jenkins build process (which starts node_modules from scratch) did not pick the change. I do not know why.

**Comment by pbeshai** [comment]
Did you try regenerating your committed lock file? (yarn.lock or package-lock.json?) If that failed let me know and we can publish this fix but one would hope that would work... :( package management woes are real

**Comment by jmcpeak** [comment]
```
use-query-params@2.1.1:
  version "2.1.1"
  resolved "https://registry.yarnpkg.com/use-query-params/-/use-query-params-2.1.1.tgz#6b9abc9b96aed5f4476a28a91e92c4d98c283a66"
  integrity sha512-6trNvHhbb9PjtNxIFA0l31A09WmafRrmcGtSPnqwKgoI7i+m741Oh3gjz9SkJFhE5FFruBWtXx7QyfmjGcI0jA==
  dependencies:
    serialize-query-params "^2.0.0"
```

This is what is in our yarn.lock file, I guess I could just update it there - `serialize-query-params "^2.0.0"`

(And thanks for your prompt responses as well)

**Comment by pbeshai** [comment]
welp easy enough to just publish, doesn't bother me. in v2.1.2 now on npm

**Pull request merged**
