### PR TITLE
fix(peer): fix peer dep of react and react dom, fix #27

### LINKED ISSUE #27: fix peerDep of react and react-dom
```jsx
"peerDependencies": {
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
  },
```

causes another react dep to be installed

moving to

```jsx
"peerDependencies": {
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0"
  },
```

fixes the issue

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by sibelius** [comment]
cc @pbeshai

**Comment by n1ru4l** [comment]
@pbeshai Sorry for bothering you, but could you please consider merging this and releasing a new version😅

**Comment by pbeshai** [comment]
Thanks, sorry for the long delay

**Comment by pbeshai** [comment]
v0.3.4 should have it, I think I forgot to publish before

**Pull request merged**
